# Generated by Django 5.1.1 on 2024-12-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_alter_utilisateur_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='datenaissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
