# Generated by Django 5.1.1 on 2024-12-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_utilisateur_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
