# Generated by Django 5.1.1 on 2024-12-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_alter_utilisateur_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
