# Generated by Django 5.1.1 on 2024-12-17 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_intervention_actif_message_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
